-- select
--
-- state_grp,
-- risk_class_grp,
-- vehicle_segment_grp,
-- accident_year,
--
-- written_premium,
--
-- written_premium / rate_level_factor
--     as onlevel_premium
--
-- from {{ ref('int_policy_exposure') }}
-- join {{ ref('int_rate_level_factor') }}
