
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'data_pipeline'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'data_pipeline'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# Project-wide variables
vars:
  calendar_start_date: '2010-01-01'
  calendar_end_date: '2031-01-01'

  as_of_date: '2023-12-31'

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  data_pipeline:

    staging:
      +materialized: view
      +tags: ["staging"]

      common:
        +tags: ["staging", "common"]

      auto:
        +tags: ["staging", "auto"]

      property:
        +tags: ["staging", "property"]


    intermediate:
      +materialized: table
      +tags: ["intermediate"]

      exposure:
        +tags: ["intermediate", "exposure"]

      claims:
        +tags: ["intermediate", "claims"]

      features:
        +tags: ["intermediate", "features"]

      actuarial:
        +tags: ["intermediate", "actuarial"]

        development:
          +tags: ["intermediate", "actuarial", "development"]

        cdf:
          +tags: ["intermediate", "actuarial", "cdf"]

        ldf:
          +tags: ["intermediate", "actuarial", "ldf"]

        triangle:
          +tags: ["intermediate", "actuarial", "triangle"]

        ultimate:
          +tags: ["intermediate", "actuarial", "ultimate"]


    core:
      +materialized: table
      +tags: ["core"]


    features:
      +materialized: table
      +tags: ["features"]



    marts:
      +materialized: table
      +tags: ["mart"]
