data_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: jtareoz-xu25676
      user: pheotter
      role: dbt_role
      database: dbt_db
      warehouse: dbt_wh
      schema: dbt_schema

      authenticator: snowflake
      private_key_path: /mnt/d/internship/airflow/dbt_project/snowflake_private_key.pem

      # 如果有設 passphrase
      # private_key_passphrase: YOUR_PASSPHRASE
